version: '3.8'

services:
  app:
    build: .
    container_name: nestjs-app
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    environment:
      # Variáveis da aplicação
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DOMAIN_URL: ${DOMAIN_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      DATABASE_URL: ${DATABASE_URL}
